add_newline = false
scan_timeout = 30

format = "$os$directory$git_branch$git_status$cmd_duration $character"

[directory]
style = "bold cyan"
format = "[$path]($style)"
repo_root_style = "bold blue"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)"
truncation_length = 3
truncate_to_repo = true

[character]
success_symbol = "[â€º](bold green)"
error_symbol = "[â€º](bold red)"

[git_branch]
style = "bold magenta"
format = " [$symbol$branch]($style)"

[git_status]
format = " [$all_status$ahead_behind]($style)"
conflicted = "[âœ–${count}](bold red) "
ahead = "[â†‘${count}](bold green) "
behind = "[â†“${count}](bold red) "
diverged = "[â†•${ahead_count}/${behind_count}](bold yellow) "
stashed = "[ğŸ“¦${count}](bold cyan) "
staged = "[+${count}](bold green) "
modified = "[!${count}](bold yellow) "
renamed = "[Â»${count}](bold blue) "
deleted = "[-${count}](bold red) "
untracked = "[?${count}](bold red) "

[battery]
disabled = true

[gcloud]
disabled = true

[cmd_duration]
min_time = 2000
format = " [$duration]($style)"
style = "dimmed yellow"

[os]
disabled = false
format = "[$symbol]($style) "
style = "dimmed white"

[os.symbols]
Macos = "ï£¿"
Linux = "ğŸ§"
